name: Build APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    # 🟢 إجبار السيرفر على توليد wrapper بنسخة 7.5 مستقرة تمنع سحب Gradle 9 العشوائي
    - name: Setup Gradle wrapper
      run: gradle wrapper --gradle-version 7.5

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MuhgoubPanel-debug
        path: app/build/outputs/apk/debug/app-debug.apk
